### ISSUE TITLE
feat: initialize a Shape for each JavaEntity

### ISSUE THREAD

**Issue by khoa-l** [Fall23csc509/CodeVillage#54]
- Extend ShapeChainLink abstract class in a ShapesInitLink class

ShapesInitLink should call appropriate ShapeFactory(s) for each Shape

**Comment by buk0vec** [comment]
Impl details:
- The top level NeighborhoodWrapper is now populated with all JavaEntities and sub-neighborhoods
- We need to create a Shape for each JavaEntity, along with a Neighborhood shape for each neighborhood
- This array of shapes and the Neighborhood shape must be saved within the NeighborhoodWrapper
- The indexes of the Shape array should correspond to the indexes of the JavaEntity array (shapes[0] contains the shape for entities[0]
- We must also initialize entity shapes and Neighborhood shapes for each sub neighborhood
