### ISSUE TITLE
feat: determine the size of each Neighborhood based on the Shape(s) inside

### ISSUE THREAD

**Issue by khoa-l** [Fall23csc509/CodeVillage#57]
- Extend ShapeChainLInk in a NeighborhoodDimensionsLink

**Comment by buk0vec** [comment]
Impl details:
    - For the deepest subneighborhoods, size will just be the total space taken up by its shapes
    - For neighborhoods with sub neighborhoods, size will be the space taken up by its shapes plus the space taken up by its sub neighborhoods, placed one after the other directly below its shapes
    - Start adding on neighborhoods after the entityYBound
    - Give each neighborhood 10px of y-padding between them, and then a final 10px of y-padding before the border
    - Store neighborhood width and height in NeighborhoodWrapper’s Neighborhood for each NeighborhoodWrapper

**Comment by buk0vec** [comment]
Basically the height is calculable by entityYBound + (size(subN) + 10) for each subN
