### ISSUE TITLE
feat: position a Neighborhood absolutely in regards to the Canvas

### ISSUE THREAD

**Issue by khoa-l** [Fall23csc509/CodeVillage#58]
- Extend the ShapeChainLink in a NeighborhoodAbsolutePositionsLink class

When the Neighborhood is moved, all Shape(s) within must also be moved by the next link

**Comment by buk0vec** [comment]
Implementation details:
- Each Neighborhood shape within each NeighborhoodWrapper contains a width and a height now
- Each NeighborhoodWrapper also contains an int entityYBound, containing the lowest y where we can start placing neighborhoods
- Determine and set centerX and centerY positions for each NeighborhoodShape based on placing subneighborhoods below the entities.
- Make sure that there is 10px of padding between neighborhoods
ex:
E E E E E
E E
[N1]
[N2]
[N3]
