### ISSUE TITLE
feat: position the Shape(s) within each Neighborhood absolutely

### ISSUE THREAD

**Issue by khoa-l** [Fall23csc509/CodeVillage#59]
- Extend the ShapeChainLink abstract class in a ShapeAbsolutePositioningLink class

Moves Shape(s) within a neighborhood on the Canvas compared to where the Neighborhood location and bounds are

**Comment by buk0vec** [comment]
Implementation details:
- Each Shape within the NeighborhoodWrapper has an X and Y that is relative to the top-left of the neighborhood
- The Neighborhood shape stored in each NeighborhoodWrapper now has a width, height, centerX, and centerY that corresponds to a location on the canvas.
- For each neighborhood:
  - Correctly position each entity from its relative position
  - Correctly position the entities in its subneighborhoods
